-- DROP TABLE IF EXISTS RESULTADOS_PROYECTOS_NOTAS;
-- DROP TABLE IF EXISTS ALUMNOS_PROMOCIONES_RESULTADOS;
-- DROP TABLE IF EXISTS CURSOS_PROYECTOS;
-- DROP TABLE IF EXISTS PROMOCIONES_PROFESORES;
-- DROP TABLE IF EXISTS PROMOCIONES;
-- DROP TABLE IF EXISTS PROFESORES;
-- DROP TABLE IF EXISTS PROYECTOS;
-- DROP TABLE IF EXISTS CURSOS;
-- DROP TABLE IF EXISTS ALUMNOS;



CREATE TABLE ALUMNOS (
  IdAlumno INTEGER PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL
);

CREATE TABLE CURSOS (
  IdCurso INTEGER PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL
);

CREATE TABLE PROYECTOS (
  IdProyecto INTEGER PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL
);

CREATE TABLE PROFESORES (
  IdProfesor INTEGER PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL,
  Rol VARCHAR(255) NOT NULL
);

CREATE TABLE PROMOCIONES (
  IdPromo INTEGER PRIMARY KEY,
  FechaComienzo DATE NOT NULL,
  Modalidad VARCHAR(255) NOT NULL,
  Campus VARCHAR(255) NOT NULL,
  IdCurso INTEGER NOT NULL,
  FOREIGN KEY (IdCurso) REFERENCES CURSOS (IdCurso)
);

CREATE TABLE PROMOCIONES_PROFESORES (
  IdPromoProfe INTEGER PRIMARY KEY,
  IdPromo INTEGER NOT NULL,
  IdProfe INTEGER NOT NULL,
  FOREIGN KEY (IdPromo) REFERENCES PROMOCIONES (IdPromo),
  FOREIGN KEY (IdProfe) REFERENCES PROFESORES (IdProfe)
);

CREATE TABLE CURSOS_PROYECTOS (
  IdCursoProyecto INTEGER PRIMARY KEY,
  IdCurso INTEGER NOT NULL,
  IdProyecto INTEGER NOT NULL,
  FOREIGN KEY (IdCurso) REFERENCES CURSOS (IdCurso),
  FOREIGN KEY (IdProyecto) REFERENCES PROYECTOS (IdProyecto)
);

CREATE TABLE ALUMNOS_PROMOCIONES_RESULTADOS (
  IdResultados INTEGER PRIMARY KEY,
  IdAlumno INTEGER NOT NULL,
  IdPromo INTEGER NOT NULL,
  FOREIGN KEY (IdAlumno) REFERENCES ALUMNOS (IdAlumno),
  FOREIGN KEY (IdPromo) REFERENCES PROMOCIONES (IdPromo)
);

CREATE TABLE RESULTADOS_PROYECTOS_NOTAS (
  Id_RPN INTEGER PRIMARY KEY,
  IdResultados INTEGER NOT NULL,
  IdProyecto INTEGER NOT NULL,
  Apto BOOL NOT NULL,
  FOREIGN KEY (IdResultados) REFERENCES ALUMNOS_PROMOCIONES_RESULTADOS (IdResultados),
  FOREIGN KEY (IdProyecto) REFERENCES PROYECTOS (IdProyecto)
);
