-- DROP TABLE IF EXISTS RESULTADOS_PROYECTOS_NOTA;
-- DROP TABLE IF EXISTS ALUMNO_PROMOCION_RESULTADOS;
-- DROP TABLE IF EXISTS CURSO_PROYECTO;
-- DROP TABLE IF EXISTS PROMOCION_PROFESOR;
-- DROP TABLE IF EXISTS PROMOCION;
-- DROP TABLE IF EXISTS PROFESOR;
-- DROP TABLE IF EXISTS PROYECTO;
-- DROP TABLE IF EXISTS CURSO;
-- DROP TABLE IF EXISTS ALUMNO;



CREATE TABLE ALUMNO 
  (
    IdAlumno int NOT NULL, 
    Nombre varchar(255) NOT NULL, 
    Email varchar(255) NOT NULL, 
    PRIMARY KEY (IdAlaumno) 
  );


CREATE TABLE CURSO 
  (
    IdCurso int NOT NULL, 
    Nombre varchar(255) NOT NULL, 
    PRIMARY KEY (IdCurso) 
  );


CREATE TABLE PROYECTO 
  (
    IdProyecto int NOT NULL, 
    Nombre varchar(255) NOT NULL, 
    PRIMARY KEY (IdProyecto) 
  );


CREATE TABLE PROFESOR 
  (
    IdProfesor int NOT NULL, 
    Nombre varchar(255) NOT NULL,
    Rol varchar(255) NOT NULL, 
    PRIMARY KEY (IdProfesor) 
  );


CREATE TABLE PROMOCION 
  (
    IdPromo int NOT NULL, 
    FechaComienzo DATE NOT NULL, 
    Modalidad varchar(255) NOT NULL, 
    Campus varchar(255) NOT NULL, 
    PRIMARY KEY (IdPromo) 
    IdCurso int FOREIGN KEY REFERENCES CURSO (IdCurso) 
  );

  CREATE TABLE PROMOCION_PROFESOR
  (
    IdPromoProfe int NOT NULL,
    PRIMARY KEY (IdPromoProfe) 
    IdCurso int FOREIGN KEY REFERENCES CURSO (IdCurso) 
    IdProyecto int FOREIGN KEY REFERENCES PROYECTO (IdProyecto) 
  )


CREATE TABLE CURSO_PROYECTO 
  (
    IdCursoProyecto int NOT NULL,
    PRIMARY KEY (IdCursoProyecto) 
    IdCurso int FOREIGN KEY REFERENCES CURSO (IdCurso) 
    IdProyecto int FOREIGN KEY REFERENCES PROYECTO (IdProyecto) 
  )



CREATE TABLE ALUMNO_PROMOCION_RESULTADOS 
  (
    IdResultados int NOT NULL,
    PRIMARY KEY (IdResultados)
    IdAlumno int FOREIGN KEY REFERENCES ALUMNO (IdAlumno)
    IdPromo int FOREIGN KEY REFERENCES PROMOCION (IdPromo) 
  );


 CREATE TABLE RESULTADOS_PROYECTOS_NOTA
  (
    Id_RPN int NOT NULL,
    PRIMARY KEY (Id_RPN) 
    IdResultados int FOREIGN KEY REFERENCES ALUMNO_PROMOCION_RESULTADOS (IdResultados) 
    IdProyecto int FOREIGN KEY REFERENCES PROYECTO (IdProyecto) 
  )



  --auto increment
  CREATE TABLE ALUMNO (
  IdAlumno INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL
);

CREATE TABLE CURSO (
  IdCurso INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL
);

CREATE TABLE PROYECTO (
  IdProyecto INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL
);

CREATE TABLE PROFESOR (
  IdProfesor INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL,
  Rol VARCHAR(255) NOT NULL
);

CREATE TABLE PROMOCION (
  IdPromo INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FechaComienzo DATE NOT NULL,
  Modalidad VARCHAR(255) NOT NULL,
  Campus VARCHAR(255) NOT NULL,
  IdCurso INT NOT NULL,
  FOREIGN KEY (IdCurso) REFERENCES CURSO (IdCurso)
);

CREATE TABLE PROMOCION_PROFESOR (
  IdPromoProfe INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  IdCurso INT NOT NULL,
  IdProyecto INT NOT NULL,
  FOREIGN KEY (IdCurso) REFERENCES CURSO (IdCurso),
  FOREIGN KEY (IdProyecto) REFERENCES PROYECTO (IdProyecto)
);

CREATE TABLE CURSO_PROYECTO (
  IdCursoProyecto INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  IdCurso INT NOT NULL,
  IdProyecto INT NOT NULL,
  FOREIGN KEY (IdCurso) REFERENCES CURSO (IdCurso),
  FOREIGN KEY (IdProyecto) REFERENCES PROYECTO (IdProyecto)
);

CREATE TABLE ALUMNO_PROMOCION_RESULTADOS (
  IdResultados INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  IdAlumno INT NOT NULL,
  IdPromo INT NOT NULL,
  FOREIGN KEY (IdAlumno) REFERENCES ALUMNO (IdAlumno),
  FOREIGN KEY (IdPromo) REFERENCES PROMOCION (IdPromo)
);

CREATE TABLE RESULTADOS_PROYECTOS_NOTA (
  Id_RPN INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  IdResultados INT NOT NULL,
  IdProyecto INT NOT NULL,
  FOREIGN KEY (IdResultados) REFERENCES ALUMNO_PROMOCION_RESULTADOS (IdResultados),
  FOREIGN KEY (IdProyecto) REFERENCES PROYECTO (IdProyecto)
);