--Visualizar todas las notas de un alumno
SELECT ALUMNOS.Nombre, PROYECTOS.Nombre, RESULTADOS_PROYECTOS_NOTAS.Apto
FROM ALUMNOS
INNER JOIN ALUMNOS_PROMOCIONES_RESULTADOS on ALUMNOS.IdAlumno = ALUMNOS_PROMOCIONES_RESULTADOS.IdAlumno
INNER JOIN RESULTADOS_PROYECTOS_NOTAS ON ALUMNOS_PROMOCIONES_RESULTADOS.IdResultados = RESULTADOS_PROYECTOS_NOTAS.IdResultados
INNER JOIN PROYECTOS ON RESULTADOS_PROYECTOS_NOTAS.IdProyecto = PROYECTOS.IdProyecto
WHERE ALUMNOS.Nombre LIKE 'Marta%'



--Cuantos alumnos hay por campus
SELECT PROMOCIONES.Campus, COUNT(ALUMNOS.IdAlumno)
from PROMOCIONES
JOIN ALUMNOS_PROMOCIONES_RESULTADOS ON PROMOCIONES.IdPromo = ALUMNOS_PROMOCIONES_RESULTADOS.IdPromo
JOIN ALUMNOS on ALUMNOS_PROMOCIONES_RESULTADOS.IdAlumno = ALUMNOS.IdAlumno
GROUP BY PROMOCIONES.Campus



--los nombres de alumnos a los que ha impartido clase cierto profesor
ALUMNOS.Nombre, PROFESORES.Nombre
FROM ALUMNOS
JOIN ALUMNOS_PROMOCIONES_RESULTADOS ON ALUMNOS.IdAlumno = ALUMNOS_PROMOCIONES_RESULTADOS.IdAlumno
JOIN PROMOCIONES_PROFESORES ON ALUMNOS_PROMOCIONES_RESULTADOS.IdPromo = PROMOCIONES_PROFESORES.IdPromo
JOIN PROFESORES on PROMOCIONES_PROFESORES.IdProfe = PROFESORES.IdProfesor
WHERE PROFESORES.Nombre LIKE 'Marta%'